# Generated by Django 3.2.7 on 2021-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(),
        ),
    ]
