# Generated by Django 3.2.7 on 2021-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210921_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='description',
        ),
        migrations.AddField(
            model_name='subtask',
            name='name',
            field=models.TextField(default='t'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.TextField(default='t'),
            preserve_default=False,
        ),
    ]
