# Generated by Django 3.2.7 on 2021-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211015_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
