# Generated by Django 3.2.7 on 2021-11-12 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_subtask_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='weight',
        ),
        migrations.CreateModel(
            name='TaskWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='api.subtask')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_weight', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
