# Generated by Django 3.2 on 2021-12-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='scoreadd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='score',
            field=models.IntegerField(default=2),
        ),
    ]
