# Generated by Django 3.2 on 2021-12-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_menti_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menti',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
