# Generated by Django 3.2 on 2022-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_menti_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='rating_0',
            field=models.CharField(choices=[('0', 'keine ausführrung'), ('1', 'gemeinsam mit dem Arzt'), ('2', 'unter Beobachtung des Arztes'), ('3', 'eigenständig')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='track',
            name='rating_1',
            field=models.CharField(choices=[('0', 'keine ausführrung'), ('1', 'gemeinsam mit dem Arzt'), ('2', 'unter Beobachtung des Arztes'), ('3', 'eigenständig')], default='0', max_length=1),
        ),
    ]
