# Generated by Django 3.2 on 2022-01-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220113_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='rating_1',
            field=models.FloatField(),
        ),
    ]
