# Generated by Django 3.2 on 2022-04-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_track_rating_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='menti',
            name='visable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='classes',
            field=models.TextField(default='ALL'),
        ),
    ]
