# Generated by Django 3.2 on 2022-04-08 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_auto_20220406_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_0', models.CharField(choices=[('0', 'ALL'), ('1', 'AUGENHEILKUNDE')], default='0', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
