# Generated by Django 3.2 on 2022-04-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_extradata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extradata',
            old_name='rating_0',
            new_name='abteilung',
        ),
    ]
