from django.urls import path
from . import views

urlpatterns = [
        path('', views.getRoutes),
        path('tasks/',views.getTasks),
        path('subtasks/',views.getSubtasks),
        path('subtasksByTask/<str:pk>/', views.getSubtasksByTask),
        path('subtasksOrderedByTask/', views.getSubtasksOrderedByTask),
        path('osubtasks/<str:pk>/', views.getOSubtasks),
        path('tracks/',views.getTracks),
        path('mentiTracks/<str:pk>/',views.getMentiTracks),
        path('tracks/create/', views.createTrack),
        path('tracks/<str:pk>/update/', views.updateTrack),
        path('tracks/<str:pk>/delete/', views.deleteTrack),
        path('tracks/<str:pk>/',views.getTrack),
        path('tracks/byTask/<str:pk>/',views.getTrackOnTask),
        path('tasks/<str:pk>/',views.getTask),
        path('subtasks/<str:pk>/',views.getSubtask),
        path('users/',views.getUsers ),
        path('users/create/', views.createUser),
        path('weights/', views.getWeights),
        path('weights/byTask/<str:mentiID>/<str:taskID>/', views.getWeightOnTask),
        path('weights/<int:count>/', views.getCountedWeights),
        path('weights/<str:pk>/delete/', views.deleteWeight),
        path('weights/<str:pk>/update/', views.updateWeight),
        path('login/', views.login_user),
        path('logout/', views.logout_user),
        path('forgotPassword/', views.forgot_password),
        path('stats/<int:count>/', views.getStats),
        path('stats/<str:pk>/<int:count>/', views.getUserStats),
        path('weightedStats/<str:pk>/<int:count>/', views.getWeightedStats),
        path('unweightedStats/<str:pk>/<int:count>/', views.getUnweightedStats),
        path('weightedUserStats/<int:count>/', views.getWeightedUserStats),
        path('unweightedUserStats/<int:count>/', views.getUnweightedUserStats),
        path('addweightscore/', views.addWeightScore),
        path('messages/<int:start>/<int:count>/', views.getMessage),
        path('mentiMessages/<int:mentiId>/<int:start>/<int:count>/', views.getUserSpecificMessage),
        path('messages/add/', views.createMessage),
        path('messages/<str:pk>/delete/', views.deleteMessage),
        path('menti/', views.getMenti),
        path('taskweight/create/', views.createTaskWeight),
        path('taskweights/user/<str:pk>/', views.getTaskWeightsOfUser),
        path('userStatus/', views.checkUserStatus),
        path('mentorid/', views.getMentorId),
]